# Generated by Django 4.0 on 2023-01-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_avataruser_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, default='settings.MEDIA_URL/avatar/avatar.png', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.avataruser'),
        ),
    ]
