# Generated by Django 4.0 on 2023-01-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_time_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_time_online',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
