# Generated by Django 4.0 on 2023-01-10 16:56

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_avataruser_default_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(default=users.models.AvatarUser.defaultImg, on_delete=django.db.models.deletion.CASCADE, to='users.avataruser'),
        ),
    ]
