# Generated by Django 4.0 on 2023-01-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.FileField(upload_to='uploads/background/')),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
