# Generated by Django 4.0 on 2023-01-10 16:56

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_backgrounduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ForeignKey(default=users.models.BackgroundUser.defaultImg, on_delete=django.db.models.deletion.CASCADE, to='users.backgrounduser'),
        ),
    ]
