# Generated by Django 4.0 on 2023-01-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('our_post', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_post.userpost'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_post.userpost'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
