# Generated by Django 4.0 on 2023-01-09 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 18, 51, 38, 463084)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 18, 51, 38, 461090)),
        ),
    ]
