# Generated by Django 4.0 on 2023-01-11 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_post', '0003_alter_postcomment_createdat_alter_userpost_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 29, 15, 742393)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 29, 15, 740398)),
        ),
    ]
