# Generated by Django 4.0 on 2023-01-10 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_post', '0007_alter_postcomment_createdat_alter_userpost_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 18, 54, 8, 531718)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 18, 54, 8, 530721)),
        ),
    ]
