# Generated by Django 4.1.1 on 2023-01-23 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmodel',
            name='sourceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchatmodel',
            name='targetId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationships',
            name='followedUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedUserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationships',
            name='followerUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followerUserId', to=settings.AUTH_USER_MODEL),
        ),
    ]
