# Generated by Django 4.0 on 2023-01-10 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_userchatmodel_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 14, 17, 3, 622144)),
        ),
    ]
