# Generated by Django 4.0 on 2022-11-19 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_userchatmodel_alter_chatmodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChatModel',
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 14, 42, 18, 894659)),
        ),
    ]
