# Generated by Django 4.0 on 2023-01-14 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_userchatmodel_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='new_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userchatmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 14, 4, 55, 9322)),
        ),
    ]
