# Generated by Django 4.0 on 2022-11-19 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chats', '0006_delete_userchatmodel_alter_chatmodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 14, 44, 57, 651047)),
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2022, 11, 19, 14, 44, 57, 652045))),
                ('content', models.CharField(max_length=350)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'user_post',
            },
        ),
        migrations.CreateModel(
            name='UserChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2022, 11, 19, 14, 44, 57, 652045))),
                ('updatedAt', models.DateTimeField(null=True)),
                ('sourceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceId', to='auth.user')),
                ('targetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetId', to='auth.user')),
            ],
            options={
                'db_table': 'user_message',
            },
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followedUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedUserId', to='auth.user')),
                ('followerUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followerUserId', to='auth.user')),
            ],
            options={
                'db_table': 'relationships',
            },
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.userpost')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'post_likes',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2022, 11, 19, 14, 44, 57, 653042))),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.userpost')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'post_comment',
            },
        ),
    ]
