# Generated by Django 4.0 on 2022-11-20 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_chatmodel_timestamp_userpost_userchatmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='base64',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 22, 28, 1, 123789)),
        ),
        migrations.AlterField(
            model_name='userchatmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 22, 28, 1, 122792)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 22, 28, 1, 123789)),
        ),
    ]
