# Generated by Django 4.0 on 2022-12-05 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_chatmodel_base64_alter_chatmodel_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 17, 24, 14, 663056)),
        ),
        migrations.AlterField(
            model_name='userchatmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 17, 24, 14, 662059)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 17, 24, 14, 663056)),
        ),
    ]
