# Generated by Django 4.0 on 2022-12-06 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_postcomment_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 30, 47, 570739)),
        ),
        migrations.AlterField(
            model_name='userchatmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 30, 47, 568744)),
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='content',
        ),
        migrations.AlterField(
            model_name='userpost',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 30, 47, 569741)),
        ),
        migrations.AddField(
            model_name='userpost',
            name='content',
            field=models.ManyToManyField(to='chats.Photo'),
        ),
    ]
