# Generated by Django 4.0 on 2022-12-06 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_alter_photo_photo_alter_postcomment_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 21, 43, 44, 6211)),
        ),
        migrations.AlterField(
            model_name='userchatmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 21, 43, 44, 4220)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 21, 43, 44, 5214)),
        ),
    ]
