# Generated by Django 4.1.1 on 2022-12-08 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_alter_photo_photo_alter_postcomment_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 11, 59, 58, 765048)),
        ),
        migrations.AlterField(
            model_name='userchatmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 11, 59, 58, 763052)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 11, 59, 58, 764052)),
        ),
    ]
