# Generated by Django 4.0 on 2022-12-09 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_alter_postcomment_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 14, 50, 7, 375348)),
        ),
        migrations.AlterField(
            model_name='userchatmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 14, 50, 7, 373353)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 14, 50, 7, 374351)),
        ),
    ]
