# Generated by Django 4.0 on 2023-01-02 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_alter_postcomment_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='userId',
        ),
        migrations.AlterField(
            model_name='userchatmodel',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 20, 24, 15, 552926)),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostLikes',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
